### ISSUE TITLE
Code Hanging on Lookups

### ISSUE THREAD

**Issue by sobpilot** [maxolidean/NoRepo#1] opened 2017-01-23 16:05 UTC
I'm new to DocumentDB and using the C# await directive. I have used NoRepo as below and I can add documents, but the code hangs on any of the get methods. This code is in a Web Forms application and I'm not sure how to use NoRepo. Any help would be appreciated.

Common class...

	public static class DocDbRepository
	{
        static string Endpoint = "https://xxxxxx.documents.azure.com:443/";
        static string Key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        static string Database = "misc";
        static string Collection = "misc";

        public static async System.Threading.Tasks.Task<pcAccount> AccountAdd(pcAccount account)
        {
            var repo = new DocumentDbRepo(Endpoint, Key, Database, Collection);
            account.id = await repo.Upsert<pcAccount>(account.id,account);
            return account;
        }

        public static async System.Threading.Tasks.Task<pcAccount> AccountGeyByEmail(string email)
        {
            var repo = new DocumentDbRepo(Endpoint, Key, Database, Collection);
            var act = await repo.FirstOrDefault<pcAccount>(c => c.Email == email.Trim());
            return act;
        }
    }

WebForm Usage...

    public partial class Account : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void _bCreate_Click(object sender, EventArgs e)
        {
            var act = new pcAccount();
            act.Name = _Name.Text;
            act.Email = _Email.Text;
            act.Password = _Password.Text;
            act.Phone = _Phone.Text;
            var cam1 = new pcCamera();
            cam1.IsActive = true;
            cam1.Description = "My Camera 1";
            cam1.Position = 10;
            cam1.url = "My URL 1";
            var cam2 = new pcCamera();
            cam2.IsActive = true;
            cam2.Description = "My Camera 2";
            cam2.Position = 10;
            cam2.url = "My URL 2";
            var Cams = new List<pcCamera>();
            Cams.Add(cam1);
            Cams.Add(cam2);
            act.Cameras = Cams;
            var a = DocDbRepository.AccountAdd(act);
        }

        protected void _bLookup_Click(object sender, EventArgs e)
        {
            var act = DocDbRepository.AccountGeyByEmail(_Email.Text).Result;
            if (act == null) return;
            _Name.Text = act.Name;
            _Password.Text = act.Password;
            _Phone.Text = act.Phone;
        }
    }

**Comment by mxldyn** [comment] 2017-01-26 15:48
Will take a look at it and come back to you soon.

**Comment by mxldyn** [comment] 2017-01-30 14:48
Question: is your collection a partitioned collection?
We are solving some issues with partitioned collections

**Comment by sobpilot** [comment] 2017-01-30 15:02
No, NOT partitioned. It looks like I am having the same trouble with the Microsoft C# SDK.

I suspect the problem is with how I am using await in my WebForm app. Here is some sample code in my underlying method...

        public static async Task<pcAccount> AccountGetByEmailX(string email)
        {
            //var client = new DocumentClient(new Uri(Endpoint), Key);
            //var db = await client.CreateDatabaseAsync(new Database { Id = Database });
            //var col = await client.CreateDocumentCollectionAsync(UriFactory.CreateDatabaseUri(Database), new DocumentCollection { Id = "collectionId" });
            //var acts = client.CreateDocumentQuery<pcAccount>(UriFactory.CreateDocumentCollectionUri(Database, Collection))
            //    .Where(x => x.Email == "steve@olis.com");
            //var act = acts.FirstOrDefault();

            var acts = await DocDbRepo<pcAccount>.GetItemsAsync(c => c.Email == "steve@olis.com");
            var act = acts.FirstOrDefault();
            return act;
        }

**Comment by mxldyn** [comment] 2017-01-30 15:17
Do you get any exception message / stack trace that we could see?

**Comment by sobpilot** [comment] 2017-01-30 17:10
No, it hangs somewhere inside the AccountGetByEmailX, probably at the await statement. Browser just spins and never times out.

**Comment by mxldyn** [comment] 2017-04-04 17:48
Will close this since we couldn't reproduce.

**Closed as completed by mxldyn** 2017-04-04 17:48 UTC
Labels: help wanted
